### PR TITLE
Add livy_server role and playbooks

### LINKED ISSUE #15: Add Livy
We could use having a role to deploy Apache Livy. It is used by Hue for example.

### PR DESCRIPTION
**Pull request by Nuttymoon**
Fixes #15 

Based on the code of @DanielJohnHarty from https://github.com/TOSIT-IO/tdp-collection/pull/205

### CODE REVIEW

**Review by leopaul36 — CHANGES_REQUESTED** [review]
Can you move `roles/livy/server/defaults/main.yml` to a new folder `tdp_extra_vars_defaults` to follow the same model as in `tdp-collection` ?

I know it's not the case for the other roles yet but livy looks a good place to start.

**Comment by Nuttymoon** [comment]
> Can you move `roles/livy/server/defaults/main.yml` to a new folder `tdp_extra_vars_defaults` to follow the same model as in `tdp-collection` ?
> 
> I know it's not the case for the other roles yet but livy looks a good place to start.

Sure

**Comment by Nuttymoon** [comment]
@gboutry @leopaul36 I added `tdp_lib_dag/livy.yml` as discussed. Can you check if this is correct?

**Review by gboutry — COMMENTED** [review]
I think the vars folder's name should be `tdp_vars_defaults`, same as in main collection.

We should keep the same name for the playbooks, the dependency graph folder, and the vars. To allow the passing of only the repository path to `tdp-lib`. It would simplify the creation of external collections that can interface with the lib.

(This feature is not yet present in `tdp-lib`)

**Review by leopaul36 — APPROVED** [review]
DAG looks good to me

**Comment by leopaul36** [comment]
> 

Agreed

**Comment by leopaul36** [comment]
> I think the vars folder's name should be `tdp_vars_defaults`, same as in main collection.
> 
> We should keep the same name for the playbooks, the dependency graph folder, and the vars. To allow the passing of only the repository path to `tdp-lib`. It would simplify the creation of external collections that can interface with the lib.
> 
> (This feature is not yet present in `tdp-lib`)

+1

**Pull request merged**
